$! MAKE_KIT.COM - build the PCSI kit for this node's architecture
$!
$! Usage:  @[.VMS.KIT]MAKE_KIT
$! Needs a built tree (@[.VMS]BUILD): the install tree [.INSTALL_<arch>] and
$! the programs in [.BIN_<arch>].  Writes the kit to [.KIT_<arch>].  The product
$! description, text module and documentation were generated by
$! tools/prepare.sh into [.VMS.KIT].
$!
$ set noon
$ status = 44
$ saved_default = f$environment("DEFAULT")
$ proc = f$environment("PROCEDURE")
$ kitdir = f$parse(proc,,,"DEVICE") + f$parse(proc,,,"DIRECTORY")
$ set default 'kitdir'
$ set default [--]
$ arch = f$edit(f$getsyi("ARCH_NAME"), "UPCASE")
$ base = "I64VMS"
$ if arch .eqs. "X86_64" then base = "X86VMS"
$!
$! KIT_PRODUCER, PCSI_VERSION, KIT_VERSION from kit.env
$ open/read env [.VMS.KIT]KIT.ENV
$env_loop:
$ read/end=env_done env line
$ name = f$element(0, "=", line)
$ 'name' = f$element(1, "=", line)
$ goto env_loop
$env_done:
$ close env
$!
$ inst = "[.INSTALL_''arch'"
$ need = "''inst'.LIB]LIBBZ2.OLB,[.BIN_''arch']BZIP2.EXE,[.BIN_''arch']BZIP2RECOVER.EXE"
$ i = 0
$need_loop:
$ f = f$element(i, ",", need)
$ if f .eqs. "," then goto need_done
$ if f$search(f) .eqs. ""
$ then
$   write sys$error "MAKE_KIT: no ''f'; build first"
$   goto done
$ endif
$ i = i + 1
$ goto need_loop
$need_done:
$!
$! Gather the files flat in [.KIT_<arch>.MAT]: PRODUCT PACKAGE looks each
$! one up by name in the material directory (destinations are in the PDF).
$ mat = "[.KIT_''arch'.MAT]"
$ out = "[.KIT_''arch']"
$ if f$search("KIT_''arch'.DIR") .eqs. "" then create/directory 'out'
$ if f$search("[.KIT_''arch']MAT.DIR") .eqs. "" then create/directory 'mat'
$ if f$search("''out'*.PCSI;*") .nes. "" then delete/nolog 'out'*.PCSI;*
$ if f$search("''mat'*.*;*") .nes. "" then delete/nolog 'mat'*.*;*
$ copy/nolog 'inst'.LIB]LIBBZ2.OLB 'mat'
$ copy/nolog 'inst'.INCLUDE]BZLIB.H 'mat'
$ copy/nolog [.BIN_'arch']BZIP2.EXE,BZIP2RECOVER.EXE 'mat'
$ copy/nolog [.VMS.KIT]BZIP2$STARTUP.COM,BZIP2$SETUP.COM,README.VMS 'mat'
$ copy/nolog [.VMS.KIT.DOC]*.* 'mat'
$ matspec = f$parse(mat,,,"DEVICE","NO_CONCEAL") + f$parse(mat,,,"DIRECTORY","NO_CONCEAL")
$!
$ write sys$output "MAKE_KIT: ''KIT_PRODUCER' ''base' BZIP2 ''PCSI_VERSION' (BZIP2 ''KIT_VERSION')"
$ product package BZIP2 -
    /producer='KIT_PRODUCER' /base_system='base' /version='PCSI_VERSION' -
    /source=[.VMS.KIT]BZIP2-'base'.PCSI$DESC -
    /material='matspec' -
    /destination='out' -
    /format=sequential -
    /options=noconfirm /log
$ status = $status
$ kit = f$search("''out'*.PCSI")
$ if kit .nes. "" then write sys$output "MAKE_KIT: kit ", kit
$ if kit .eqs. "" then status = 44
$done:
$ set default 'saved_default'
$ exit status
